services:
  - type: web
    name: invoice-extractor-api
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.15

  - type: web
    name: invoice-extractor-frontend
    env: static
    buildCommand: "echo 'Frontend build complete'"
    staticPublishPath: .
    envVars:
      - key: RENDER_STATIC_PUBLISH_PATH
        value: frontend